# Generated by Django 3.2.9 on 2021-11-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211124_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlist',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantlist',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantlist',
            name='disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantlist',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
