# Generated by Django 3.2.9 on 2021-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211124_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlist',
            name='menu_list',
            field=models.TextField(default=None),
        ),
    ]
