# Generated by Django 3.2.9 on 2021-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restaurantlist_menu_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlist',
            name='menu_list',
            field=models.TextField(default=None, null=True),
        ),
    ]
